### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by reubwn** [jamiemcg/BUSCO_phylogenomics#1]
Hi, thanks for the useful script! I was just wondering how to cite the program? Is there an associated paper or is a URL to this GitHub page OK?

Cheers,
Reuben

**Comment by jamiemcg** [comment]
Hi @reubwn,

Glad you found it useful! I added some info to the readme if you need a paper or DOI to cite
https://github.com/jamiemcg/BUSCO_phylogenomics#citation

Cheers,
Jamie

**Comment by reubwn** [comment]
Thanks!
