### ISSUE TITLE
Nucleotide option

### ISSUE THREAD

**Issue by jamiemcg** [jamiemcg/BUSCO_phylogenomics#11]
TODO: 
Add a flag `--nt` to align nucleotide sequences of BUSCOs instead of amino acids

**Comment by alexandergofton** [comment]
@jamiemcg is there a plan to implement this soon? It would be sooo useful!

**Comment by alexandergofton** [comment]
Resolved in my fork of the repo. Added --nt flag with uses the .fna rather than the .faa to produce alignments.

**Comment by bheimbu** [comment]
Hi @alexandergofton,

I'd like to use this. How would I do it?


Cheers Bastian
