### ISSUE TITLE
BUSCOphylogenomics.py can't find BUSCO results?

### ISSUE THREAD

**Issue by jdoyle30724** [jamiemcg/BUSCO_phylogenomics#16]
Hi!  I hope you are doing well today.  I was wondering exactly what results or sequence of directories BUSCOphylogenomics.py -i is looking for.  I have a directory called BUSCO_test_results with the output of BUSCO runs.  However, I keep receiving ERROR: didn't find any BUSCO directories. Here (https://gvolante.riken.jp/script/result.cgi?202410170717-A4FZ19WCU5LU1JTL) is a link to some of the results I have from the gVolante server (if you scroll down you can download a .zip file of the raw BUSCO results)... what should I include so that BUSCOphylogenomics.py can proceed?

Alternatively, do you have some example BUSCO results that could be posted, so that I can check that I am not experiencing an installation error?

Best!

**Comment by jdoyle30724** [comment]
Hi again,

Okay, I've determined that if I put "run_" at the beginning of my directories, BUSCOphylogenomics.py can find my directories.  But then, it seems to be trying to follow a path that ends with ".../run_some_name/busco_sequences/busco_sequences/single_copy_busco_sequences".  Do you know how to address this issue?  My output is attached.

Best!

![Screenshot 2024-10-17 144141](https://github.com/user-attachments/assets/a5176372-5017-420a-a7ed-5000527a4e3f)

**Comment by jdoyle30724** [comment]
Hi again,

Okay, it looks like directories should be organized as follows:

"run_orca_results/test/busco_sequences/single_copy_orthologs"

The "run" part in the first directory name seems to be important, as do the directory names "busco_sequences" and "single_copy_orthologs" for the last two directories.  The rest seems to be flexible.

Best!

**Comment by jamiemcg** [comment]
Hi @jdoyle30724,

The pipeline expects the BUSCO results to be organised they same way they are output by default by the BUSCO tool.

Normally BUSCO outputs results in this sort of format:

```GENOME_ID/run_eukaryota_odb10/busco_sequences/single_copy_busco_sequences/```

The gVolante server results look like they are formatted slightly differently. Having the `run_*` directory is important because that's how the BUSCO_phylogenomics pipeline knows where to look for `busco_sequences/single_copy_busco_sequences/*.faa`

You should then collect all of your BUSCO results directory into the same directory.

Here's an example:

```
BUSCO_RESULTS/
├── BUSCO4_EP00006_Acanthamoeba_castellanii.fasta
│		 ├── run_
│		 │		 ├── busco_sequences
│		 │		 │		 └── single_copy_busco_sequences
├── BUSCO4_EP00023_Dictyostelium_discoideum.fasta
│		 ├── run_
│		 │		 ├── busco_sequences
│		 │		 │		 └── single_copy_busco_sequences
├── BUSCO4_EP00035_Acanthoeca_spectabilis.fasta
│		 ├── run_
│		 │		 ├── busco_sequences
│		 │		 │		 └── single_copy_busco_sequences
.....
.....
.....
```

Run BUSCO_phylogenomics pipeline:

```python BUSCO_phylogenomics.py --input BUSCO_RESULTS --output BUSCO_PHYLOGENOMICS --threads 8```
