### ISSUE TITLE
Error : No such file or directory exist.

### ISSUE THREAD

**Issue by athulmenon** [jamiemcg/BUSCO_phylogenomics#2]
Hi,

Thanks for this script. I was trying to run this, I have kept 4 BUSCO runs I have completed with "hypocreales" as the lineage. I kept all the "run_" folders into one folder and tried to run the script. But an error shows "No such file or directory exist". Can you please look into this?

`python BUSCO_phylogenomics.py -d busco_runs -o Phylogeny_results --supermatr
ix -t 10 -l hypocreales
100
18-01-2021 11:36:45	Starting BUSCO Phylogenomics Pipeline
Found 4 BUSCO runs:
	run_hypocreales_odb10
	run_hypocreales_odb10_FequisetiNCBI
	run_hypocreales_odb10_Fgraminearum
	run_hypocreales_odb10_FOxysporum

Traceback (most recent call last):
  File "BUSCO_phylogenomics.py", line 369, in <module>
    main()
  File "BUSCO_phylogenomics.py", line 122, in main
    os.chdir("run_" + lineage)
FileNotFoundError: [Errno 2] No such file or directory: 'run_hypocreales'
`

Regards,
Athul

**Comment by jamiemcg** [comment]
Hi @athulmenon,

Can you try with ` -l hypocreales_odb10`

**Comment by aberaslop** [comment]
Hi, 

I am having the same problem (#3). @athulmenon, did you find a way to fix this? Using "-l hypocreales_odb10", did not work for me, unfortunately. 

Thanks!
