### ISSUE TITLE
Alignment not loaded

### ISSUE THREAD

**Issue by aberaslop** [jamiemcg/BUSCO_phylogenomics#4]
Hi @jamiemcg,

I have added new species to the super matrix analysis, and somehow I have encountered a new problem. 
I believe something is failing at the time of making the alignments. The script and the terminal output are copied on the attached file. I am not sure what is different from last time beyond the number and identity of some of the species. 
[BUSCO_phylogenomics.log](https://github.com/jamiemcg/BUSCO_phylogenomics/files/6217760/BUSCO_phylogenomics.log)
Any help is really appreciated.

A.

**Comment by hmedwards** [comment]
Hello. I am having this same issue. Did you ever find a solution?
Thanks!

**Comment by bgenevcius** [comment]
I believe I have the same issue. I get hundreds of "ERROR: Alignment not loaded: "alignments_4/10594at7524.aln" Check the file's content." and all alignments folders are empty. Any solution?

**Comment by aberaslop** [comment]
Hi!
I have two installations of busco_phylogenomics in different servers. I have run the exact same data in both servers and one ran perfectly fine and the other stopped at the "ERROR: Alignment not loaded:". I reasoned that the problem must have been at the muscle step, since the alignments were not being produced. Digging a bit online i found this: AstrobioMike/GToTree#47. I compared both installations and indeed saw that the working one was running muscle v3.8.1551 and the second muscle v 5.1. Downgrading muscle to v3.8.1551 did the trick and now the second installation produces alignments! 
I hope this helps!

**Comment by bgenevcius** [comment]
Hi Jamie,

I was about to write to you today. I tested your suggestion yesterday and
it worked! I just changed the muscle flags in your script and everything
worked. Thank you so much.
cheers
*Bruno C. Genevcius, PhD *
*http://www.genevcius.xyz/* <http://www.genevcius.xyz/>
Postdoctoral Researcher
Lab of Gene Expression and Evolution in Arthropods (http://torres.ib.usp.br/
)
Department of Genetics and Evolutionary Biology
University of São Paulo, Brazil




Em qui., 21 de abr. de 2022 às 12:24, aberaslop ***@***.***>
escreveu:

**Comment by jamiemcg** [comment]
This issue was due to muscle v5 changing the input and output parameters. Now they are `-align` and `-output`, compared to perviously `-in` and -`out`.

If have now modified the `BUSCO_phylogenomics.py` script to work for muscle v5.
